### ISSUE TITLE
[BUG] Accept appointment failed if entering a room or recource

### ISSUE THREAD

**Issue by KarstenPoschmann** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#112]
Hello,

I have the following issue with DOMI.

**HCL Product Version**
HCL Notes 12 with German Notes 12 Mailtemplate

**Describe the bug**
If I create a meeting with DOMI and append a room or recourse the meeting will create successfully. But after sending the appointment I cannot change it and every customer using also a Notes Client will get the following message if they want to accept the meeting:
"Bitte wählen Sie einen Online-Besprechungsbereich für diese Online Besprechung"

**To Reproduce**
1. Create an appointment
2. Create DOMI Meeting (e.g. Teams, GoTo Meeting)
3. Select an internal room or recource
4. Send the appointment
5. try to change it or try to accept the meeting with a Notes Client

**Expected behavior**

**Screenshots**
The error message:
![grafik](https://user-images.githubusercontent.com/90388335/132672550-c9fbaa16-9474-4a9f-8599-6d84f6c66877.png)
The problem might be in this LS part:
![grafik](https://user-images.githubusercontent.com/90388335/132672643-016781b0-844b-4689-b9d6-3882a87eb00f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

Kind regards
Karsten Poschmann

**Comment by spanky762** [comment]
Hi @KarstenPoschmann:   This seems similar to issue #104, which has been resolved.  Are you sure you are running the latest release code?

**Comment by INeedCaffeine** [comment]
This may be fixed in 12.0.1 Beta 1.  I recall working on it but I forget if it got fixed for Beta 1 or after.

**Comment by KarstenPoschmann** [comment]
Thank you, I have implement the new code and now it works
