### ISSUE TITLE
[BUG] Error into TOKEN

### ISSUE THREAD

**Issue by grydan** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#114]
**HCL Product Version**
11.0.1FP3

**Describe the bug**
When I paste the token generated from your HCL app for Microsoft Teams

**Error Message**
token invalid

**To Reproduce**

1. Download NSF from here ==> https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/tree/main/release
2. unzip and new copy  or new replica to my server customer
3. SIGN with Domino admin with full access 
4. Deploy to users
5. When the user (template mail 11.0.1) create a new credential ==> get the Microsoft Login ==> and after generate a Token 
6. Return to Notes and paste Token

Replica

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37438497/133633724-42f36927-3535-4c1a-a6d5-84545671b8ec.png)
![token_oauth](https://user-images.githubusercontent.com/37438497/133633752-870cba57-6b4e-4db0-8630-8cd55ec52a4a.png)

**Desktop (please complete the following information):**
 - OS: Windows
**Additional context**

**Comment by spanky762** [comment]
@grydan :  Please verify you are using the latest DOMI release.  (Open DOMI.nsf in designer, open Script library "domiConstantsBE", and check the following constant values:

Private Const g_DOMI_VERSION 			= |1.0.5|
Private Const g_DOMI_BUILD 			= |1.1588|
Private Const g_DOMI_RELEASE_DATE 	= |18 August 2021|

The error you are describing was resolved with pull request #91 on 20 July 2021.

**Comment by grydan** [comment]
I have downloaded today from this ZIP

https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/blob/main/release/DOMI.zip

Is correct?

**Comment by grydan** [comment]
![image](https://user-images.githubusercontent.com/37438497/133641098-b09062f6-416f-4c4e-8630-f113f64b93a1.png)

**Comment by grydan** [comment]
the relase is correct

**Comment by spanky762** [comment]
Hmmm.   Something seems incorrect then.  I pulled it down myself and ran through your steps, and it worked fine for me.   

Would you please set the Notes.ini property 
DOMI_LOG_LEVEL=600 

Then attempt to create your Teams credentials and OAuth token again?  After you get the failure then please check your local notes log (log.nsf) and send me the results?  devin.olson@hcl.com

**Comment by grydan** [comment]
I understand.
The notes client is installed in multi-user mode.
So missing cacert.pem in the PATH….
Can you confirm me this theory and install a notes 11.0.3FP3 in multi user modality.
Tomorrow I’ll retest

**Comment by grydan** [comment]
I've write to you an email: is not a problem about cacert.pem

**Comment by grydan** [comment]
The problem is the PROXY like your docs:
https://support.hcltechsw.com/csm?id=kb_article&sys_id=4f9be010db7cec50a45ad9fcd39619b0&spa=1
