### ISSUE TITLE
Cannot open included file: "lsconst.lss"

### ISSUE THREAD

**Issue by jmcxw** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#115]
This error message appears when tried to add credentials in the DOMI View in mail db. This only happens with Notes 11.0.1 FP3 on MacOS BigSur. It is reproducable, I've made a clean reinstallation already but it didn't help. The file "lsconst.lss" doesn't seem to exist on MacOS installations.
![2021-09-20 10_03_26-MacBook-Pro localdomain - TeamViewer](https://user-images.githubusercontent.com/87766612/134033832-36af73e6-a20b-40e5-b547-24918377172d.png)

**Comment by spanky762** [comment]
What version notes are you running on your mac?  

If you open finder, then show all files (CTRL + SHIFT + Period), then go to /Applications, right-click on "HCL Notes.app", and choose "Show Package Contents".  From within the Contents you should be able to expand Resources, and find the *.lss files there.  

![image](https://user-images.githubusercontent.com/3831901/134688474-75854d9d-7143-417a-a30c-b389140cafc0.png)

**Comment by spanky762** [comment]
Perhaps try a "Recompile All LotusScript" and let us know the results.

**Comment by jmcxw** [comment]
"Recompile All LotusScript" not really possible, there is no Designer for MacOS. Also checked content of the file, looks just the same as the file on my windows installation. Tried to change the rights on the file from Read to Write, but that didn't change the error from coming up.
