### ISSUE TITLE
Meeting invite body should use plain display text

### ISSUE THREAD

**Issue by BerndGewehr** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#124]
**HCL Product Version**
12.0.1 beta

**Describe the bug**
Currently, DOMI places this as the body of a created teams meeting:

`Online meeting: <a href=\"https://teams.microsoft.com/l/meetup-join/<meetingId>\">https://teams.microsoft.com/l/meetup-join/<meetingId></a>`

This does not lead to displaying a "join" button on the Zoom Room with calendar integration active.

Whenever I changed the link like this:

`Online meeting: <a href=\"https://teams.microsoft.com/l/meetup-join/<meetingId>\">Join Meeting</a>`

the join button appeared on the Zoom Room. 

**Error Message**
No Error Message, just no join button on Zoom Room

**To Reproduce**
1. Create a room ressource in an O365 tenant
2. Create a zoom admin user in the same tenant and delegate the resource mailbox with full right to that user
3. Add the zoom admin user account in your Zoom Rooms account settings and add the ressource
4. Link the ressource to a Zoom Room
5. Allow show meeting calendar on TV to see the event buttons
6. Create person in NAB with the name of the room, other internet mail, forwarding to the external ressource mailbox
7. allow automatic external invite approval via exchange powershell for the ressource mailbox
8. Invite the room as a person in a new calender invite and add a teams meeting with DOMI
9. See the meeting appear on the Zoom Room without a button to join it
10. Correct the meeting link so that the display text is plain text
11. See the updated event with a join link

**Expected behavior**
Meetings created with DOMI should work well in the Zoom Room calendar integration

**Screenshots**
![image](https://user-images.githubusercontent.com/21081707/138449881-d5165e1b-2771-40c2-b2e3-facff644c771.png)

**Additional context**
https://support.zoom.us/hc/en-us/articles/203847179#h_8c244740-44f6-4419-a5fb-a856a63ff34d

**Comment by INeedCaffeine** [comment]
Please keep us informed about what you hear back.
