### ISSUE TITLE
Nginx error on this page https://domi.hcllabs.live//dominoTeams/index.html

### ISSUE THREAD

**Issue by RenatoCasati** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#127]
**HCL Product Version**
Notes 11 FP3

**Describe the bug**
During the authentication of token I receive the error attached

**Error Message**
Page Unavailable

**To Reproduce**
Renew the token

**Expected behavior**
The error started on 02 november 2021 

**Screenshots**
![image](https://user-images.githubusercontent.com/93645608/140032130-70fbcd97-4ec7-44ef-80a2-02b29b3e4eba.png)

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by INeedCaffeine** [comment]
It should be working now.

You probably should update your template to point to HCLs official servers: https://integration-auth-token.hcltechsw.com
