### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gpawlak** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#132]
**HCL Product Version**
Version: 		Release 12.0; May 14, 2021             ; Build 461

**Describe the bug**
I can create a new document for an online service. 
I choose "Teams", press "Get OAuth token", the page opens correctly, 
I copy the token, paste it to "Refresh token". 
Then I have an error "Your OAuth token appears to be invalid". 
In console.log everything looks good. 
In log.nsf I see following errors. It looks like $ meeting is empty.

**Error Message**
2021.11.16 17:03:55 LotusScript Started
2021.11.16 17:03:55 Error #1195: A passed parameter is invalid.  Unsupported Meeting Service.  
Library: domiUtilsBE.GETDOMINODENAMESTOCOPY();  line #70
Meeting Service: 

Stack Logging is Disabled

2021.11.16 17:03:55 
Error #4848: Wystąpił problem z protokołem SSL. Aby uzyskać więcej informacji, włącz ustawienie śledzenia debugowania Debug_NotesHTTPRequest
Library: NotesRESTconsumer.Class: NotesRESTconsumer.GETREQUESTRESPONSE();  line #204
GET: https://integration-auth-token.hcltechsw.com/dominoZoomRefresh

Stack Logging is Disabled

2021.11.16 17:03:55 Error #4848: Wystąpił problem z protokołem SSL. Aby uzyskać więcej informacji, włącz ustawienie śledzenia debugowania Debug_NotesHTTPRequest
Library: NotesRESTconsumer.Class: NotesRESTconsumer.PROCESSREQUEST();  line #309
GET https://integration-auth-token.hcltechsw.com/dominoZoomRefresh

**Screenshots**

![domi](https://user-images.githubusercontent.com/919374/142211140-b0740da3-f2c0-4c9e-ba8e-0c5ab2b86273.jpg)

**Desktop (please complete the following information):**
 - OS: Win 10

**Comment by tkheuer** [comment]
I had this issue with Notes 11.01 FP3
Perhaps this helps:
If you use a multi language Notes client you have to copy over the C:\ProgramData\HCL\Notes\Data\Shared\cacert.pem to each C:\ProgramData\HCL\Notes\Data\Shared\MUI\<language> directory

**Comment by gpawlak** [comment]
It works!!
Thank you very much
Grzegorz

**Comment by gpawlak** [comment]
it is solved
