### ISSUE TITLE
Mail database of v12.0 with Domino Online Meeting Integration by domi.nsf upgraded to 12.0.1 ignores pervious configuration documents for DOMI

### ISSUE THREAD

**Issue by sujitanbhule** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#145]
We extended the mail template of version 12.0 with the with Domino Online Meeting Integration (domi.nsf).
After that the users configured their access to MS Teams which created a DOMI configuration document, the integration with meetings in calendar and MS Teams worked perfectly after that.

By upgrading to the mail template of 12.0.1 we have DOMI just integrated by HCL - should be perfect, but:
the integration does not work as it wont accept the previously created (in v12.0) DOMI configuration document and the client error is being logged to local log.nsf:
2021.12.29 06:13:24 Error #1401: The HTTP Request operation has failed.  
Library: domiIntegrator.Class: DominoOnlineMeetingIntegrator.DOMEETINGREQUESTRAW();  line #899
HTTP/1.1 400 Bad Request

The only solution is to go to the hidden view with alias "DOMI_uiMeetingCredentials" and re-save the MS Teams configuration document, after that the DOMI integration works. 
We cannot tell a hundreds of users to do that.

Is there an automatic way to "upgrade" DOMI from 12.0 to 12.0.1 without user interaction ?

**Comment by spanky762** [comment]
With the release of 12.0.1, DOMI changed from using the previous configuration document model to a Profile Document model.  My guess (as I am not in Product Dev) is that the configuration document form was modified in 12.0.1 to force a save of information to the Profile document.   I understand the frustration regarding the scalability of having all your users edit and re-save their configuration documents.   I will notify Product Dev of this issue.

Hope this helps!

**Comment by INeedCaffeine** [comment]
The data format used in 12.0.1 is different from the original DOMI data model.  We have no current plans to do automatic data migration of the original DOMI data to the format used in Notes.  That means end users will need to create new DOMI credential docs when switching to the official DOMI release.  Any further discussion of this should be done through a support case.

**Comment by spanky762** [comment]
Users must re-create their credentials profile information in 12.0.1
