### ISSUE TITLE
[BUG] Install DOMI only lists nsf databases

### ISSUE THREAD

**Issue by damien-gm** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#153]
**HCL Product Version**
Notes 12.0.1 FP1, macOS and Windows 11, Notes 11.0.1 SHF92 on Windows

**Describe the bug**
After opening the DOMI database, and pressing Install DOMI, the dialog box to select which file to apply DOMI on only shows nsf (database) files, not template files (nft) as per the instructions suggest.

**Error Message**
no error message

**To Reproduce**
1. Open DOMI nsf database
2. Go to main page
3. Press Install DOMI
4. See file selection dialog box only show nsf databases, regardless which server you look in, or any folder.

**Expected behavior**
List both nsf and nst. Instructions for installation to be updated as such.

**Screenshots**
![image](https://user-images.githubusercontent.com/68585985/172997023-1e97d41a-aff0-4685-819b-32519e5c9c76.png)

**Desktop (please complete the following information):**
All

**Comment by spanky762** [comment]
This is an issue with dialog boxes, they only display NSF file types when opening an application on a server.  Not a DOMI specific issue.   Note: Any valid file name can be typed into the file name field.
