### ISSUE TITLE
LifeSize meetings integration

### ISSUE THREAD

**Issue by robdeloin** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#154]
Bonjour.

Is it possible to think about a LifeSize meetings integration ?
LifeSize works smoothly from Windows, App, WebRTC, SIP, H323 ...

Regards.

**Comment by INeedCaffeine** [comment]
@robdeloin : It looks like LifeSize does have an API ( I found it mentioned at https://legacy.lifesize.com/en/icon-help/advanced-topics-api-overview ) but they certainly do not make it easy to find by searching their web site or using a moderate amount of Google-fu.   

As Devin already mentioned you should use AHA to request adding that service to DOMI officially.  If you want to give it a try yourself you should find it a fairly straightforward process to update the 12.0.1 template once you know what REST calls to make for the various actions.
