### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EspositoLS** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#161]
**HCL Product Version**
HCL Notes v. 12.01.FP1

**Describe the bug**
DOMI Integration whit Webex - Unregistered client with webex.
Randomly the HCL Notes client lost the Join with webex, with Invalid Token message in the log.
The user have to repeat the procedure of token request and Join in the client.

**Error Message**
No error message displayed, in the LOG we see "Invalid Token message".

We have collected only this case, on Client Log:
[log di maso.txt](https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/files/10824425/log.di.maso.txt)

**To Reproduce**
Not Reproducible, random

**Expected behavior**

**Screenshots**
![Hcl integration](https://user-images.githubusercontent.com/126253731/221187145-33d68a96-734a-45c4-ad97-309fea84e89e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 64 Bit.

**Additional context**
![Webex Hcl integration declaration](https://user-images.githubusercontent.com/126253731/221187159-54e6c4e6-9069-42e1-a766-602e70a261bb.jpg)

Tank you for any possible suggestions or resolution.

**Comment by paulswithers** [comment]
For 12.0.1, that's part of the core mail template and support is handled by HCL Support directly for that version. If I remember correctly, it's now using profile documents for where the tokens are stored, if that information is useful for identifying how to reproduce it.
