### ISSUE TITLE
[BUG]Webex Connection Failure

### ISSUE THREAD

**Issue by yvderlet** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#44]
**HCL Product Version**
11.01FP3

**Describe the bug**
Unable to create Online Meeting with Webex

**Error Message**
If an error message is displayed, include details here. Quickly identifying the code causing the error will help to more quickly resolve it.

**To Reproduce**
1. Go to 'Calendar
2. Create a new Meeting
3. Add a subject
4. Click on Online Meeting
5. Get the first message
6. If you click Validate 

**Expected behavior**

**Screenshots**
![Screenshot 2021-06-17 131720](https://user-images.githubusercontent.com/84967618/122388475-35c01680-cf70-11eb-96e5-9a8eefc2ea35.png)
![Screenshot 2021-06-17 132033](https://user-images.githubusercontent.com/84967618/122388482-36f14380-cf70-11eb-8814-d2490c670c4a.png)

**Desktop (please complete the following information):**
 Windows 10 HCL Notes 1101 FP3

**Additional context**

**Comment by yvderlet** [comment]
Hello Paul,

what can be the cause of the OAuth failure ? I update with the new code and get the same issue.

We do not have a Sametime Meeting server, we use Webex on cloud.

Thank you

**Comment by spanky762** [comment]
As I understand it, you are still experiencing a problem with this.  

I am re-opening this issue. 

Will you please edit your notes.ini file and add the following:
DOMI_LOG_LEVEL=600 

After saving your notes.ini file, please restart your notes client and perform you attempted operation again.  

If it still fails, a log entry (or entries) with information about your attempt will be written to your notes log (log.nsf).  Can you please post the log content here (you may edit / excise any identifying information as needed).  

Hope this helps!

**Comment by yvderlet** [comment]
Hello,

I replace again de design today and regenerate the OAuth and it seems to 
work fine.

I wonder if the problem was not in the Copy / Paste button that allow to 
copy / Paste the URL...

I copy and paste manually (CTRLC - CTRL V)

I will make another test with another user and will give oyu a feedback.

If I have the error, I will set the logging parameter and send you the 
log.

Best regards / Salutations

Yves Derlet
Collaboration software Engineer



From:   "Devin S. Olson" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-online-meeting-integration" 
***@***.***>
Cc:     "yvderlet" ***@***.***>, "Author" 
***@***.***>
Date:   18/06/2021 16:23
Subject:        Re: [HCL-TECH-SOFTWARE/domino-online-meeting-integration] 
[BUG]Webex Connection Failure (#44)




CAUTION: This email originated from outside of Cebi IT infrastructure and 
therefore could be unsafe. Do not follow guidance, click links, or open 
attachments unless you recognize the sender and know the content is safe.


As I understand it, you are still experiencing a problem with this.
I am re-opening this issue.
Will you please edit your notes.ini file and add the following:
DOMI_LOG_LEVEL=600
After saving your notes.ini file, please restart your notes client and 
perform you attempted operation again.
If it still fails, a log entry (or entries) with information about your 
attempt will be written to your notes log (log.nsf). Can you please post 
the log content here (you may edit / excise any identifying information as 
needed).
Hope this helps!

**Comment by spanky762** [comment]
Hello Yves.

Yes, that is likely the problem.  The paste button not only pastes the content into the field, but then also triggers an OAuth validation agent to verify the Refresh Token is valid.  

If you manually paste the Refresh Token into the field, just refresh the form (F9) and that will cause a "Validate OAuth Token" Action Button to become visible.   Clicking that button will then trigger the OAuth validation agent.  

Hope this helps!

**Comment by spanky762** [comment]
Please let me know if this resolves the issue.   Thanks!

**Comment by yvderlet** [comment]
Hello,

I have updated the mail template with the Online Meeting feature and apply 
it to some users.

But if I go to Online Meeting view to configure it, I have errors 
messages.



Do I have to do specific actions for each new user ?

Thank you
Best regards / Salutations

Yves Derlet
Collaboration software Engineer



From:   "Devin S. Olson" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-online-meeting-integration" 
***@***.***>
Cc:     "yvderlet" ***@***.***>, "Author" 
***@***.***>
Date:   18/06/2021 16:56
Subject:        Re: [HCL-TECH-SOFTWARE/domino-online-meeting-integration] 
[BUG]Webex Connection Failure (#44)




CAUTION: This email originated from outside of Cebi IT infrastructure and 
therefore could be unsafe. Do not follow guidance, click links, or open 
attachments unless you recognize the sender and know the content is safe.


Please let me know if this resolves the issue. Thanks!

**Comment by spanky762** [comment]
Hello Yves. 

Yes, each user must individually create / authenticate their own individual OAuth token for their Online Meeting Configuration document (1 document per service, per user mail file). 

Hope this helps!

**Comment by yvderlet** [comment]
Hello,

I agree that I need to create the OAuth profile for each user.

But I have the error message when I want to create it on a new user.

I update the template file with the design elements but do I have to 
generate profile or other actions before users can creste their OAuth 
profile ?

Best regards / Salutations

Yves Derlet
Collaboration software Engineer



From:   "Devin S. Olson" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-online-meeting-integration" 
***@***.***>
Cc:     "yvderlet" ***@***.***>, "Author" 
***@***.***>
Date:   23/06/2021 23:51
Subject:        Re: [HCL-TECH-SOFTWARE/domino-online-meeting-integration] 
[BUG]Webex Connection Failure (#44)




CAUTION: This email originated from outside of Cebi IT infrastructure and 
therefore could be unsafe. Do not follow guidance, click links, or open 
attachments unless you recognize the sender and know the content is safe.


Hello Yves.
Yes, each user must individually create / authenticate their own 
individual OAuth token for their Online Meeting Configuration document (1 
document per service, per user mail file).
Hope this helps!

**Comment by yvderlet** [comment]
Hello,

I try again on other users and get the same issue.... impossible to 
validate the token....

What can I do for debugging ?

I try to set the notes.ini parameter... without any additional info in 
log.nsf....


Best regards / Salutations

Yves Derlet
Collaboration software Engineer



From:   "Devin S. Olson" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-online-meeting-integration" 
***@***.***>
Cc:     "yvderlet" ***@***.***>, "Author" 
***@***.***>
Date:   18/06/2021 16:54
Subject:        Re: [HCL-TECH-SOFTWARE/domino-online-meeting-integration] 
[BUG]Webex Connection Failure (#44)




CAUTION: This email originated from outside of Cebi IT infrastructure and 
therefore could be unsafe. Do not follow guidance, click links, or open 
attachments unless you recognize the sender and know the content is safe.


Hello Yves.
Yes, that is likely the problem. The paste button not only pastes the 
content into the field, but then also triggers an OAuth validation agent 
to verify the Refresh Token is valid.
If you manually paste the Refresh Token into the field, just refresh the 
form (F9) and that will cause a "Validate OAuth Token" Action Button to 
become visible. Clicking that button will then trigger the OAuth 
validation agent.
Hope this helps!

**Comment by yvderlet** [comment]
Hello,

I come back to you concerning this issue.

I had it working fine on my mailbox, but impossible to do ti to other users, also on mine...

What do I wrong concerning the Copy / Paste function ?

Thank you

**Comment by yvderlet** [comment]
Hello,

I set the DOMI_LOG_LEVEL=600... but I do not see anything in the log.nsf....

Can we make a remote session for perhaps clarifying the way ?

thank you

**Comment by spanky762** [comment]
Hello Yves.  
I agree, at this point we should try to set up some time to review this together.  

This is the beginning of a holiday weekend here in the US, and I suspect you have already shut down for the day.  Let us try for upcoming Tuesday.

**Comment by yvderlet** [comment]
Hello,

I already set the DOMI_LOG:DEBUG=600... but no logs....

It is perhaps because I'm using the full client (Notes + Design +Admin)...

Can we make a remote session Tuesday afternoon ? 2pm ?

Thank you

Best regards / Salutations

Yves Derlet
Collaboration software Engineer



From:   "Devin S. Olson" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-online-meeting-integration" 
***@***.***>
Cc:     "yvderlet" ***@***.***>, "Author" 
***@***.***>
Date:   02/07/2021 19:50
Subject:        Re: [HCL-TECH-SOFTWARE/domino-online-meeting-integration] 
[BUG]Webex Connection Failure (#44)




CAUTION: This email originated from outside of Cebi IT infrastructure and 
therefore could be unsafe. Do not follow guidance, click links, or open 
attachments unless you recognize the sender and know the content is safe.


Hello Yves.
I agree, at this point we should try to set up some time to review this 
together.
This is the beginning of a holiday weekend here in the US, and I suspect 
you have already shut down for the day. Let us try for upcoming Tuesday.

**Comment by yvderlet** [comment]
Hello,

any news ?

Best regards / Salutations

Yves Derlet
Collaboration software Engineer



From:   "Devin S. Olson" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-online-meeting-integration" 
***@***.***>
Cc:     "yvderlet" ***@***.***>, "Author" 
***@***.***>
Date:   02/07/2021 19:50
Subject:        Re: [HCL-TECH-SOFTWARE/domino-online-meeting-integration] 
[BUG]Webex Connection Failure (#44)




CAUTION: This email originated from outside of Cebi IT infrastructure and 
therefore could be unsafe. Do not follow guidance, click links, or open 
attachments unless you recognize the sender and know the content is safe.


Hello Yves.
I agree, at this point we should try to set up some time to review this 
together.
This is the beginning of a holiday weekend here in the US, and I suspect 
you have already shut down for the day. Let us try for upcoming Tuesday.

**Comment by spanky762** [comment]
Good morning Yves.  
2 PM US Eastern?   

Please send me your email address and I will set up a calendar invite.  devin.olson@hcl.com

**Comment by spanky762** [comment]
Based on our conversation yesterday, we believe the problem to be due to the libCurl implementation and a known Proxy Server issue:  https://support.hcltechsw.com/csm?id=kb_article&sys_id=4f9be010db7cec50a45ad9fcd39619b0&spa=1

**Comment by yvderlet** [comment]
Hello Devin,

as I explained you, all Internet traffic is routed to Cisco Umbrella and 
we do not have any proxy settings defined on our PC.

So, either we add an exception to the URL queried by the Validate button, 
or the problem is other...

If you make a test on your side, what IP are queried ?



In the log, I have the following IP adresses :


0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] Trying 52.204.90.22...
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] TCP_NODELAY set
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] connect to 52.204.90.22 port 443 failed: Connection 
refused
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] Trying 52.6.56.188...
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] TCP_NODELAY set
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] connect to 52.6.56.188 port 443 failed: Connection 
refused
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] Trying 52.71.28.102...
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] TCP_NODELAY set
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] connect to 52.71.28.102 port 443 failed: Connection 
refused
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] Failed to connect to urldefense.com port 443: Connection 
refused
[0110:0002-1798] LSXBE HTTP debug information type: Generic Information: 
[0110:0002-1798] Closing connection 0

If I see the printscreen "testing https://urldefense.com... ", may it be 
that we are using Proofpoint Email Gateway with URL Defense ?

Thank you

Best regards / Salutations

Yves Derlet
Collaboration software Engineer



From:   "Devin S. Olson" ***@***.***>
To:     "HCL-TECH-SOFTWARE/domino-online-meeting-integration" 
***@***.***>
Cc:     "yvderlet" ***@***.***>, "Author" 
***@***.***>
Date:   08/07/2021 16:20
Subject:        Re: [HCL-TECH-SOFTWARE/domino-online-meeting-integration] 
[BUG]Webex Connection Failure (#44)




CAUTION: This email originated from outside of Cebi IT infrastructure and 
therefore could be unsafe. Do not follow guidance, click links, or open 
attachments unless you recognize the sender and know the content is safe.


Based on our conversation yesterday, we believe the problem to be due to 
the libCurl implementation and a known Proxy Server issue: 
https://support.hcltechsw.com/csm?id=kb_article&sys_id=4f9be010db7cec50a45ad9fcd39619b0&spa=1

**Comment by spanky762** [comment]
Good morning Yves.  

Would you please try pulling down the latest DOMI release code, verify the Notes.ini logging settings are correct, and use the test agent in the DOMI database to verify your HTTP responses?  

I suspect with your proxy it is going to fail.   Can you then please try setting the windows environment variables as described in the technote and let me know your results.  

Our implementation uses libcurl (and not browser)  for back-end REST connection .

**Comment by spanky762** [comment]
Yves: we posted a hotfix last night.  While you are likely still having the proxy issue, would you please pull this latest code down and give it a test?  

-Devin.

**Comment by spanky762** [comment]
Closing this issue.
