### ISSUE TITLE
[BUG] man compile jib:dockerBuild fails on CentOS

### ISSUE THREAD

**Issue by paulswithers** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#46]
**Describe the bug**
Fails with error tags cannot assign string 1.0.1 to tags

**Error Message**
![image](https://user-images.githubusercontent.com/3721367/122525545-3f4d8b00-d011-11eb-9f4a-1354f204859c.png)

**To Reproduce**
Cannot reproduce on Mac

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by eknori** [comment]
I tried to build on CentOS 7.9 not Windows

**Comment by paulswithers** [comment]
Updated the subject. Latest release includes the fix
