### ISSUE TITLE
[BUG] getNewSTTokens does not verify the user entered a username and password before trying to get a Sametime token. 

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#51]
**HCL Product Version**
12.0 Daily Build

**Describe the bug**
When creating a new Online Meeting Credentials doc for Sametime, the form pulls a default email address from the Location doc.  If the user tries to get a Sametime token without providing a password OR if they remove the default value from the dialog box then the request to Sametime will fail because there are either invalid or insufficient credentials.  The user is then shown a cryptic error dialog like this:

![image](https://user-images.githubusercontent.com/2994465/122623416-d7b73000-d050-11eb-8e2a-071691ec544a.png)

**Error Message**
A passed parameter is invalid. Unable to parse JSON [in GETNEWSTTOKENS] [E: 1195, L: 21]

**To Reproduce**
1. Go to the Online Meeting Credentials view
2. Click on New Meeting Credentials
3. Set the service to Sametime
4. Click on Get Sametime Token
5. Do NOT enter any password OR remove the login email
6. Click OK
7. See the error dialog

**Expected behavior**
The script library should check that the user entered both a username and password before it attempts to make a call to the Sametime service to get a token.

**Screenshots**
See above.

**Desktop (please complete the following information):**
Win10 Enterprise

**Additional context**
The fix for this is to add the following lines after the ws.DialogBox response code check and before any other work:

	If Trim( curdoc.GetItemValue( "loginEmail" )(0) ) = "" Then Error ERR_MISSING_USERNAME, MSG_MISSING_USERNAME
	If Trim( curdoc.GetItemValue( "stPassword" )(0) ) = "" Then Error ERR_MISSING_PASSWORD, MSG_MISSING_PASSWORD

Don't forget to add those values to the domiConstants.  I added:

Const ERR_MISSING_USERNAME = 1008
Const MSG_MISSING_USERNAME = |A username is required to get a token.  |

Const ERR_MISSING_PASSWORD = 1009
Const MSG_MISSING_PASSWORD = |A password is required to get a token.  |

**Comment by spanky762** [comment]
Resolved with code in pull request #61
