### ISSUE TITLE
[BUG] getNewSTTokens does not properly handle 400 and 401 error responses (there is no JSON to parse)

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#52]
**HCL Product Version**
12.0 Daily Build

**Describe the bug**
If the user enters invalid or incomplete Sametime credentials when trying to get a Sametime token, they will get an unhelpful error dialog that mentions "unable to parse JSON".

**Error Message**
A passed parameter is invalid. Unable to parse JSON [in GETNEWSTTOKENS] [E: 1195, L: 21]

This is the same error from issue #51.  It happens when the response code from the Sametime Meeting server is a 400 ("Invalid") or 401 ("Unauthorized").  A 401 happens when the password is not the correct one.  A 400 happens if either or both credentials are empty.

**To Reproduce**
1. Go to the Online Meeting Credentials view
2. Click on New Meeting Credentials
3. Set the service to Sametime
4. Click on Get Sametime Token
5. Enter an incorrect password
6. Click OK
7. See the error dialog

**Expected behavior**
The user should see a more descriptive error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/2994465/122623903-c96a1380-d052-11eb-86f2-be0ae5e65855.png)

**Desktop (please complete the following information):**
Win10 Enterprise

**Additional context**
The code in getNewSTTokens does not adequately check the response code before it tries to handle any error cases.  It assumes that there is always JSON in the response which is not always true.

The fix for this is to do a better check of the HTTP response code by adding the following lines after the httpRequest.Post() call:

```
	rint = nrcParseResponseCode( httpRequest.Responsecode )
	If rint = 401 Or rint = 400 Then Error ERR_INVALID_CREDENTIALS, MSG_INVALID_CREDENTIALS 
```
In addition, this line:

`	If InStr(httpRequest.Responsecode, "200") = 0 Then`

should be replaced by this to keep things clean:

`	If rint <> 200 Then `

Don't forget to add this to the domiConstants library:

Const ERR_INVALID_CREDENTIALS = 1006
Const MSG_INVALID_CREDENTIALS = |The provided credentials are invalid.  |

**Comment by spanky762** [comment]
Resolved with code in pull request #61
