### ISSUE TITLE
[BUG] The Close button prompts the user if they want to save the credentials doc or not.

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#53]
**HCL Product Version**
12.0 Daily Build

**Describe the bug**
A Notes user who sees both a **Save & Close** and a **Close** button expects that clicking on Close will simply discard the doc without any further action.  However if the user creates a new Online Meeting Credentials doc and then either get some credentials (valid or not) OR they simply make some changes before clicking on the **Close** button will be show the "Do you want to save" dialog with Yes, No and Cancel options.  This is not the expected behavior for **Close**.

**Error Message**
The user is prompted if they want to save their changes to the doc or not.  There should be no prompt.

**To Reproduce**
1. Go to the Online Meeting Credentials view
2. Click on New Meeting Credentials
3. Select a service (e.g. Sametime)
4. Click on Get Sametime Token
5. Enter invalid credentials (e.g. the user forgot their password and tried a guess)
6. Clear any error dialog that displays
7. Click on Close on the Action Bar
8. The user is prompted about saving the doc or not.

**Expected behavior**
The open Online Meeting Credentials window should simply close and anything on it discarded.

**Desktop (please complete the following information):**
Win10 Enterprise

**Additional context**
The fix for this is to change the script on the Close button from:

`@Command([CloseWindow])`

to:

```
FIELD SaveOptions := "0";
@Command([CloseWindow])

```

**Comment by spanky762** [comment]
Resolved with Pull Request #67
