### ISSUE TITLE
[BUG] The Online meeting URL do not display in the Online Meeting section until the user presses F9

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#54]
**HCL Product Version**
12.0 Daily Build

**Describe the bug**
After adding any online meeting the Notes Calendar entry has its Location and Online Meeting sections updated to contain the online meeting info.  The data in Location refreshes properly but the data in the Online Meeting section does not; it only partly updates.  The user needs to press F9 to get Notes to refresh the entry and properly show the updated Online Meeting contents.

**Error Message**
N/A

**To Reproduce**
1. Go to the Calendar
2. Click on New / Meeting
3. Enter some subject text then click on Schedule Online Meeting in the action bar.
4. Select any service from list of available choices
5. Clear the Success dialog
6. The Location and Online Meeting sections update but only the Location displays the meeting URL.
7. Press F9.  The Online Meeting section will refresh and display the online meeting URL.

**Expected behavior**
The Online Meeting section of the form should display the newly added meeting URL without any extra steps on the users part.

**Screenshots**
What the user sees:
![image](https://user-images.githubusercontent.com/2994465/122624918-41d2d380-d057-11eb-89a2-f2f23785679f.png)

What the user expects to see:
![image](https://user-images.githubusercontent.com/2994465/122624923-47c8b480-d057-11eb-8cba-ca30cae01a60.png)

**Desktop (please complete the following information):**
Win10 Enterprise

**Additional context**
The problem is due the action buttons not telling Notes to refresh all fields on the doc.  The fix is to change all of the Action Bar entries on the DOMI_onlineMeetingActions subform so they end with:

```
@Command([RefreshHideFormulas]);
@Command( [ViewRefreshFields] )
```

and not just:

`@Command([RefreshHideFormulas])`

**Comment by spanky762** [comment]
Resolved with code in pull request #61
