### ISSUE TITLE
[BUG] The list of possible services is saved to an entry once used.  If the user removes a service, it will still be listed if the user edits the entry later.  Attempting to use the missing service results in an error.

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#55]
**HCL Product Version**
12.0 Daily Build

**Describe the bug**
When a calendar entry is created it will get a confList item that contains a fixed list of online meeting services.  If the user removes or adds any services after the entry is first created then they will see an incorrect list of available meeting services under the Schedule Online Meeting... button.

**Error Message**
If the user tries to use a service that no longer has a credentials doc:
Problem obtaining auth Token from Online Meeting Credentials

The user does not see any online meeting services that have been added since the entry was created and saved.

**To Reproduce**
1. Go to Calendar
2. Click on New
3. Fill in the Subject
4. Click on Save and Send Invitations (no need to add any invitees or actually use the meeting service)
5. Go to the Online Meetings Credentials view
6. Delete the credentials for any online meeting service
7. Go back to the Calendar
8. Open the entry created in step 2
9. Click on Schedule Online Meeting... and select the service removed in step 6
10. See error

**Expected behavior**
The list of services available to the user should not be saved in a static list to the entry.  The list of services should be recreated each time the entry is opened.  That will guarantee that the user only see available meeting services.

In the case of removing the credentials after the meeting services was used to create an online meeting, the **Delete <ServiceName> Meeting** button should remove the online meeting info even if the credentials are no longer available.  When the updates are sent to invitees they will see there is no longer an online meeting which is better than them seeing a meeting that is no longer usable.

**Screenshots**
![image](https://user-images.githubusercontent.com/2994465/122625303-5a43ed80-d059-11eb-8b3d-824a0dc73ae1.png)

**Desktop (please complete the following information):**
 Win10 Enterprise

**Additional context**
The fix for this is to remove the confList item from the entry when the entry is saved.  That will cause the list of usable services to be recreated each time the entry is opened.  Removing the confList item requires a change to the core mail template scripts and is not something that DOMI may be able to without some risk.

**Comment by spanky762** [comment]
Resolved with code in pull request #61
