### ISSUE TITLE
[BUG] The Sametime credentials dialog displays the users password in the clear

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#56]
**HCL Product Version**
12.0 Daily Build

**Describe the bug**
When attempting to get a Sametime token the user is prompted to provide their Sametime username and password.  The password field is not obfuscated so what the user types is visible to anyone who is shoulder surfing.

**Error Message**
N/A

**To Reproduce**
1. Go to the Online Meeting Credentials view
2. Click on New Meeting Credentials
3. Select Sametime as the service
4. Click on Get Sametime Token on the action bar
5. Go to the password field and type something

**Expected behavior**
No password field should ever display in the clear.  Users do not expect to see their passwords on the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/2994465/122625778-af80fe80-d05b-11eb-8653-45a3a61da990.png)

**Desktop (please complete the following information):**
 Win10 Enterprise

**Additional context**
The fix for this is to simply change the stPassword field on the (domiSTLoginDlg) form to be a type Password instead of type Text.

**Comment by spanky762** [comment]
Resolved with code in pull request #61
