### ISSUE TITLE
How to activate SSL for the vert.x?

### ISSUE THREAD

**Issue by paulswithers** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#60]
### Discussed in https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **eknori** June 18, 2021</sup>
Don‘t see any obvious setting. I have config.json on a Docker volume mapped as domi:/domiconfig.d
Pfx cert is in same location than config.json and entries in the config file are present.

I just need a way to activate SSL so that the isSSL() method becomes true. 
Cannot find any ENV var (like DEBUG )</div>

Fix needed

**Comment by spanky762** [comment]
Resolved with feature pull request #65
