### ISSUE TITLE
MS Teams Audio Access

### ISSUE THREAD

**Issue by MIpk01** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#76]
Hi,
MS Teams integration works for me. Please add Audio Access information.
i use a simple helper application on the notes client to access the tenant and get back the ms meeting details.
I think the code need to retrieve this data and puts this to the body field on the calendar form:
Example from my c# code:
   if (deserializedProduct.audioConferencing != null)
                    {
                        Console.WriteLine($"audioConferencing.conferenceId: {deserializedProduct.audioConferencing.conferenceId}");
                        Console.WriteLine($"audioConferencing.tollNumber: {deserializedProduct.audioConferencing.tollNumber}");
                        Console.WriteLine($"audioConferencing.tollFreeNumber: {deserializedProduct.audioConferencing.tollFreeNumber}");
                        Console.WriteLine($"audioConferencing.dialinUrl: {deserializedProduct.audioConferencing.dialinUrl}");
                    }
The i format the output like this in the body field:
---------------------------------------
Join Microsoft Teams Meeting: https://teams.microsoft.com/l/meetup-join/19%3ameeting_xxxxxxxxxxx
Name der MS Teams Besprechung: TEST
Organisator: dummy@dummy.de
Telefon Conference ID: 123456789
Telefon Einwahlnummer: +49 12 345678901
Telefon Einwahlnummern Info: https://dialin.teams.microsoft.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
---------------------------------------

Happy Coding!

**Comment by spanky762** [comment]
Resolved by PR #80
