### ISSUE TITLE
[BUG] Sametime subject cleanup does not work

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#83]
**HCL Product Version**
12.0

**Describe the bug**
If I have a meeting subject of "@Home" (or just "@") and I try to book a Sametime Meeting, the request will fail with an HTTP 403 error.  

The problem is due to the subject that is sent on the request.  It still contains the @ character which is not allowed by the ST server / APIs.

Looking at the enhanced logging output I see that the @ was not removed from the subject that was sent:

Body JSON
{
  "meeting":{
    "name":"**@Home**_BKAN-C4VRZQ",
...

**To Reproduce**
1. Create a new meeting and give it a subject of just @ (or @Home )
2. Click on Schedule Online Meeting / Sametime
3. See error

**Expected behavior**
I would expect unsupported characters to be filtered out by the cleanupSTMeetingName() routine.  Unsupported characters like @ are supposed to be replaced by that routine but they are not.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise

**Additional context**
The failure happens because the logic in cleanupSTMeetingName() is incorrect.  It **only** makes the last string change in badList() due to this incorrect For loop:

	ForAll b In badList
		cleansubj = Replace(subj, ListTag(b), b)
	End ForAll

All replacements except for the last one are lost because the code reuses the starting input string as the string to modify instead of the modified copy.  The fix for this is to change this block of code to be:

	cleansub = subj

	ForAll b In badList
		cleansubj = Replace( cleansubj, ListTag(b), b)
	End ForAll

That way **all** string replacements will be performed instead of just blanks to underscores.

**Comment by spanky762** [comment]
Resolved by pull request #88
