### ISSUE TITLE
[BUG] > and < are not filtered from Sametime subjects

### ISSUE THREAD

**Issue by INeedCaffeine** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#84]
**HCL Product Version**
12.0

**Describe the bug**
If my meeting subject includes either a < or > character (e.g. "Chocolate > Vanilla") then I get an error trying to schedule a Sametime meeting.

**Error Message**
Problem creating meeting (HTTP/1.1 403 Forbidden) [E: 1403; L: 115]

**To Reproduce**
1. Create a new meeting and give it the subject "Chocolate > Vanilla" 
2. Click on Schedule Online Meeting / Sametime
3. See error

**Expected behavior**
I would expect any unsupported characters for a Sametime meeting to be filtered out by cleanupSTMeetingName().  The current list of filtered characters is incomplete.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win10 Enterprise

**Additional context**
The enhanced logging output for the failed request is:

2021/07/13 14:14:59 Library: NotesRESTconsumer.Class: NotesRESTconsumer.PROCESSREQUEST(): 
Response Code: HTTP/1.1 403 Forbidden
2021/07/13 14:14:59 Error #4842: Unable to Parse JSON string: 
Invalid value. offset 0

Library: NotesRESTconsumer.Class: NotesRESTconsumer.PROCESSREQUEST();  line #371
POST https://stpoc.cwp.pnp-hcl.com/meeting-catalog/api/v1/meetings
HTTP/1.1 403 Forbidden

Stack Logging is Disabled

URL: https://stpoc.cwp.pnp-hcl.com/meeting-catalog/api/v1/meetings
Method: POST
response: Forbidden
strippedResponse: Forbidden
responseCode: HTTP/1.1 403 Forbidden

Headers JSON
{
  "accept":"application/json",
   "X-CSRF-Token":"**********",
  "cookie":"_csrf=**********; sametimeJwt=**********; Max-Age=7200; Domain=*****; Path=/; Expires=Tue, 13 Jul 2021 23:14:58 GMT; HttpOnly; Secure; SameSite=None",
  "Content-Type":"application/json"
}

Body JSON
{
  "meeting":{
    "name":"Chocolate_&amp;gt;_Vanilla_BKAN-C4VSWT",
    "moderators":[
     "bruce.kahn@pnp-hcl.com"
    ],
    "allowGuestUser":false,
    "mode":"Open"
  }
}

In the JSON body we can see the subject has been HTML encoded, twice.  The > was converted to its HTML equivalent of &gt; and then the ampersand was also encoded so the final sequence contains &amp;gt;  

Since ampersands are not allowed by the Sametime REST API this causes the request to be rejected.  

The list of characters filtered by cleanupSTMeetingName() looks to be the one the Sametime web UI shows.  It does not take into account that some characters, when encoded, will result in unsupported characters being used.

The fix is simply to add these 2 lines:

	' Adding  < > to avoid HTML encoding of them before sending 
	badList("<") = "_"
	badList(">") = "_"

into cleanupSTMeetingName() before the For loop that does the cleanup work.

**Comment by spanky762** [comment]
Resolved by pull request #88
