### ISSUE TITLE
[BUG] Typo in enhLogClass.lss "[LocalCliient]" in Lines 2346 and 2403

### ISSUE THREAD

**Issue by patrickschneider** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#86]
Typo in enhLogClass Scriptlibrary:
[LocalCliient] should probably be [LocalClient]
https://github.com/HCL-TECH-SOFTWARE/domino-online-meeting-integration/blob/main/notes/Code/ScriptLibraries/enhLogClass.lss

**Comment by spanky762** [comment]
Resolved with Pull Request #87
