### ISSUE TITLE
[BUG]Zoom Authorization - Get OAuth Token

### ISSUE THREAD

**Issue by LH441996** [HCL-TECH-SOFTWARE/domino-online-meeting-integration#92]
**HCL Product Version**
12

**Describe the bug**
![Zoom Token](https://user-images.githubusercontent.com/87799965/126600100-826da83d-ea1f-4947-b733-647a4b0f5d07.PNG)

**Error Message**
We cant create a Token for Zoom, please read the following steps and note the screenshot
![Zoom Token](https://user-images.githubusercontent.com/87799965/126600358-08ae96ad-a79e-4956-a29d-249b8e27ed2b.PNG)

**To Reproduce**
1. Go to 'Online Meeting Credentials'
2. Click on 'New Meetings Credentials.'
3. Choose Zoom
4. Click on "Get OAuth Token"
5. See error in browser

**Comment by paulswithers** [comment]
We're still working with Zoom to get the application authorised for their marketplace. This is documented on the README for the repo. Once it's approved (which should not be much longer) I'll update that.

**Comment by paulswithers** [comment]
Zoom is now approved
